language: go
sudo: false

go:
  - 1.12.x
  - master

before_install:
  - curl https://glide.sh/get | sh
  - glide install

script:
  - bash test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)